import { FontDetector } from "../../lib/FontDetector"

const detector = new FontDetector()

// Alphabetically sorted array of common fonts from Windows, macOS, Android, and iOS
export const availableFonts = [
  "Agency FB",
  "American Typewriter",
  "Andale Mono",
  "Apple Chancery",
  "Arial",
  "Arial Black",
  "Avenir",
  "Bahnschrift",
  "Baskerville",
  "Bauhaus 93",
  "Bell MT",
  "Berlin Sans FB",
  "Big Caslon",
  "BlinkMacSystemFont",
  "Bodoni MT",
  "Book Antiqua",
  "Bookman Old Style",
  "Brush Script MT",
  "Calibri",
  "Calibri Light",
  "Calisto MT",
  "Cambria",
  "Candara",
  "Century Gothic",
  "Century Schoolbook",
  "Chalkboard",
  "Chalkduster",
  "Chiller",
  "Cochin",
  "Colonna MT",
  "Comic Sans MS",
  "Consolas",
  "Constantia",
  "Cooper Black",
  "Copperplate",
  "Copperplate Gothic Bold",
  "Copperplate Gothic Light",
  "Corbel",
  "Courier",
  "Courier New",
  "Curlz MT",
  "Didot",
  "Droid Sans",
  "Droid Sans Mono",
  "Droid Serif",
  "Forte",
  "Franklin Gothic Medium",
  "Freestyle Script",
  "French Script MT",
  "Futura",
  "Gabriola",
  "Garamond",
  "Geneva",
  "Georgia",
  "Gigi",
  "Gill Sans",
  "Gill Sans MT",
  "Goudy Old Style",
  "Helvetica",
  "Helvetica Neue",
  "Herculanum",
  "High Tower Text",
  "Hoefler Text",
  "Impact",
  "Iowan Old Style",
  "Lucida Console",
  "Lucida Grande",
  "Lucida Handwriting",
  "Lucida Sans Unicode",
  "Marker Felt",
  "Menlo",
  "Microsoft Sans Serif",
  "Monaco",
  "MS Sans Serif",
  "MS Serif",
  "Noto Sans",
  "Noteworthy",
  "Onyx",
  "Optima",
  "Palace Script MT",
  "Palatino",
  "Palatino Linotype",
  "Papyrus",
  "Perpetua",
  "Phosphate",
  "Pristina",
  "Ravie",
  "Rockwell",
  "Roboto",
  "Sathu",
  "San Francisco",
  "Script MT Bold",
  "Segoe Print",
  "Segoe Script",
  "Segoe UI",
  "Silom",
  "Sitka",
  "Sitka Banner",
  "Sitka Display",
  "Sitka Heading",
  "Sitka Small",
  "Sitka Subheading",
  "Sitka Text",
  "Skia",
  "Symbol",
  "Tahoma",
  "Times New Roman",
  "Trattatello",
  "Trebuchet MS",
  "Tw Cen MT",
  "Verdana",
  "Webdings",
  "Wide Latin",
  "Wingdings",
  "Zapfino",
].filter(font => detector.detect(font))
